name: Full Application Testing - Api - Realtime, frontend 

on:
  push:
    branches: 
      - main
      - auto-testing
  pull_request:
    branches:
      - main
      - auto-testing

jobs:
  # Backend Api Tests
  backend-api-tests:
    name: Backend API Tests
    runs-on: windows-latest

    steps:
      - name: Checkout code 
        uses: actions/checkout@v4 
        with:
          dotnet-version: '10.9.x'
      
      - name: Restore Dependencies
        run: dotnet restore backend/api/api.csproj

      - name: Build Backend Api
        run: dotnet build backend/api/api.csproj --configuration Release --no-restore

      - name: Run API Tests
        run: dotnet test backend/api.Tests/api.Tests.csproj  
  
# realtime Chat Tests
  realtime-chat-tests:
    name: realtime chat Tests
    runs-on: windows-latest

    steps:
      - name: Checkout code 
        uses: actions/checkout@v4 
        with:
          dotnet-version: '10.9.x'
      
      - name: Restore Dependencies
        run: dotnet restore backend/realTimeChat/realTimeChat.csproj

      - name: Build Backend realTimeChat
        run: dotnet build backend/realTimeChat/realTimeChat.csproj --configuration Release --no-restore

      - name: Run realTimeChat Tests
        run: dotnet test backend/realTimeChat.Tests/realTimeChat.Tests.csproj

# realtime notification Tests
  realtime-notification-tests:
    name: realtime notification Tests
    runs-on: windows-latest

    steps:
      - name: Checkout code 
        uses: actions/checkout@v4 
        with:
          dotnet-version: '10.9.x'
      
      - name: Restore Dependencies
        run: dotnet restore backend/realtimeNotification/realtimeNotification.csproj

      - name: Build Backend realtimeNotification
        run: dotnet build backend/realtimeNotification/realtimeNotification.csproj --configuration Release --no-restore

      - name: Run realtimeNotification Tests
        run: dotnet test backend/realtimeNotification.Tests/realtimeNotification.Tests.csproj

# Frontend Cypress Tests 
  frontend-e2e-tests:
    name: Frontend E2E Tests (Cypress)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code 
        uses: actions/checkout@v4 
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      
      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci
      

      - name: Build Angular app
        working-directory: ./frontend
        run: npm run build

      - name: Run Cypress Tests
        working-directory: ./frontend
        run: npm run e2e:ci
